import type { Metadata } from "next";
import "./globals.css";
import { cabinFont } from "./fonts";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cabinFont.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
